spring:
  # ?????
  datasource:
    url: jdbc:mysql://124.221.15.13:3306/cookercome?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: cookercome
    password: 998877
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Spring Security ????
  security:
    user:
      name:
      password:
  # ??????
  mvc:
    pathmatch:
      matching-strategy:

# ?????
server:
  port: 8080 # ????????????
  servlet:
    context-path: /api # ????????????? /api

# MyBatis ??
mybatis:
  mapper-locations: classpath:mapper/*.xml # Mapper XML ????
  type-aliases-package: com.cooker.entity # ????????? XML ???
  configuration:
    map-underscore-to-camel-case: true # ???????????? user_id ? userId?
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ?? SQL ???????

# Knife4j ??????
knife4j:
  enable: true
  openapi:
    title: ?????????????
    description: ?????????????????????
    version: v1.0
    contact:
      name: ???

